(* This file was auto-generated by wzgen *)
open Core

type struct_strength =
  | BUNKER
  | HARD
  | MEDIUM
  | SOFT

let struct_strength_of_string s =
  match s with
  | "BUNKER" -> BUNKER
  | "HARD" -> HARD
  | "MEDIUM" -> MEDIUM
  | "SOFT" -> SOFT
  | s -> raise (Invalid_argument s)
;;

type struct_type =
  | COMMAND
  | CORNER
  | CYBORG
  | DEFENSE
  | DEMOLISH
  | FACTORY
  | FACTORY_MODULE
  | GATE
  | GENERIC
  | HQ
  | LASSAT
  | MISSILE_SILO
  | POWER_GENERATOR
  | POWER_MODULE
  | REARM_PAD
  | REPAIR_FACILITY
  | RESEARCH
  | RESEARCH_MODULE
  | RESOURCE_EXTRACTOR
  | SAT
  | VTOL
  | WALL

let struct_type_of_string s =
  match s with
  | "COMMAND" -> COMMAND
  | "CORNER" -> CORNER
  | "CYBORG" -> CYBORG
  | "DEFENSE" -> DEFENSE
  | "DEMOLISH" -> DEMOLISH
  | "FACTORY" -> FACTORY
  | "FACTORY_MODULE" -> FACTORY_MODULE
  | "GATE" -> GATE
  | "GENERIC" -> GENERIC
  | "HQ" -> HQ
  | "LASSAT" -> LASSAT
  | "MISSILE_SILO" -> MISSILE_SILO
  | "POWER_GENERATOR" -> POWER_GENERATOR
  | "POWER_MODULE" -> POWER_MODULE
  | "REARM_PAD" -> REARM_PAD
  | "REPAIR_FACILITY" -> REPAIR_FACILITY
  | "RESEARCH" -> RESEARCH
  | "RESEARCH_MODULE" -> RESEARCH_MODULE
  | "RESOURCE_EXTRACTOR" -> RESOURCE_EXTRACTOR
  | "SAT" -> SAT
  | "VTOL" -> VTOL
  | "WALL" -> WALL
  | s -> raise (Invalid_argument s)
;;

type t =
  { id : string
  ; armour : Weapon_types.weapon_class -> int
  ; breadth : int
  ; buildPoints : int
  ; buildPower : int
  ; height : int
  ; hitPoints : int
  ; name : string
  ; resistance : int
  ; typ : struct_type
  ; strength : struct_strength
  ; sensorId : string option
  ; width : int
  }

let dmg_modifier (w : Weapon_types.t) (strength : struct_strength) =
  let open Weapon_types in
  match w.effect, strength with
  | FLAMER, SOFT -> Pct.of_int 150
  | FLAMER, MEDIUM -> Pct.of_int 60
  | FLAMER, HARD -> Pct.of_int 10
  | FLAMER, BUNKER -> Pct.of_int 300
  | BUNKER_BUSTER, SOFT -> Pct.of_int 100
  | BUNKER_BUSTER, MEDIUM -> Pct.of_int 120
  | BUNKER_BUSTER, HARD -> Pct.of_int 300
  | BUNKER_BUSTER, BUNKER -> Pct.of_int 400
  | ARTILLERY_ROUND, SOFT -> Pct.of_int 200
  | ARTILLERY_ROUND, MEDIUM -> Pct.of_int 120
  | ARTILLERY_ROUND, HARD -> Pct.of_int 100
  | ARTILLERY_ROUND, BUNKER -> Pct.of_int 40
  | ANTI_TANK, SOFT -> Pct.of_int 75
  | ANTI_TANK, MEDIUM -> Pct.of_int 50
  | ANTI_TANK, HARD -> Pct.of_int 25
  | ANTI_TANK, BUNKER -> Pct.of_int 60
  | ANTI_PERSONNEL, SOFT -> Pct.of_int 160
  | ANTI_PERSONNEL, MEDIUM -> Pct.of_int 65
  | ANTI_PERSONNEL, HARD -> Pct.of_int 40
  | ANTI_PERSONNEL, BUNKER -> Pct.of_int 50
  | ALL_ROUNDER, SOFT -> Pct.of_int 130
  | ALL_ROUNDER, MEDIUM -> Pct.of_int 100
  | ALL_ROUNDER, HARD -> Pct.of_int 100
  | ALL_ROUNDER, BUNKER -> Pct.of_int 75
;;

